name: Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: piyushagr0905
          outputs: github-contribution-grid-snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "generate snake"
          add: "github-contribution-grid-snake.svg"
